### ISSUE TITLE
Using import-export lib

### ISSUE THREAD

**Issue by khaled-hayek** [app-generator/django-admin-soft-pro#2]
In lib:  https://django-import-export.readthedocs.io/en/latest/

The buttons needs to have some styling

![dfbdb](https://user-images.githubusercontent.com/3869302/230964295-080b31e4-a80a-4c91-9243-e059e3f8823e.JPG)

**Comment by app-generator** [comment]
Fixed in *v1.0.7*. 
@khaled-hayek  please use the latest version.
